#!/usr/bin/env python

import sys

from rqt_gantry.manual_control_gui import GantryGuiPlugin
from rqt_gui.main import Main

plugin = 'rqt_gantry'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
